# .github/workflows/daily-build.yml

name: Daily build

on:
  schedule:
    - cron: "0 0 * * *" # 每天 0 点执行
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    # 这一步很重要，给 Action 赋予写权限，以便它可以推送 commit
    permissions:
      contents: write

    steps:
      # 步骤 1: 检出当前仓库的代码
      # 这一步现在非常标准，不需要任何额外参数
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 设置 Node.js 环境
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          # 注意：缓存路径依然需要正确设置
          cache-dependency-path: "adblock-list-generator/package-lock.json"

      # 步骤 3: 安装依赖
      # 仍然需要指定工作目录，因为 package.json 在子文件夹里
      - name: npm install
        run: npm install
        working-directory: ./adblock-list-generator

      # 步骤 4: 运行生成脚本
      - name: Generate adblock list
        run: npm run generate
        working-directory: ./adblock-list-generator

      # 步骤 5: 提交并推送文件
      - name: Commit & Push
        working-directory: ./adblock-list-generator
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # `git add .` 会添加文件夹内所有新生成和修改的文件
          git add .
          # `|| echo "No changes to commit"` 防止在没有文件变动时报错
          git commit -m "chore: update adblock list" -a || echo "No changes to commit"
          git push
