name: auto-update clash

on:
  schedule:
    - cron: "0 6 * * *"         # 06:00 UTC
  workflow_dispatch:             # 手点按钮
  repository_dispatch:           # 也可以被 API 触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install deps
        run: |
          pip install --upgrade pip pyyaml requests

      - name: debug raw
        run: |
          echo "SUB_URL=$SUB_URL"
          echo ">>> raw content head <<<"
          curl -sSL "$SUB_URL" | head -100
          echo ""
          echo ">>> end of head <<<"

      - name: fetch & filter
        run: |
          python filter.py

      - name: commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add a.yaml
          git commit -m "auto clash update $(date -u +%F_%T)" || true
          git push
